predictive_maintenance:
  outputs:

    dev:
      type: trino
      method: ldap  # optional, one of {none | ldap | kerberos}
      user: "marlon.gutjahr03@gmail.com/accountadmin"
      password: "kid+2rFa2W~SVNj"  # required if method is ldap or kerberos
      database: "predictive_maintenance"
      host: "projectsetup-project1cluster.trino.galaxy.starburst.io"
      port: 443
      schema: "public"
      threads: 1
      cert: true


  target: dev
